const english = {
  "Name": "Name",
  "No Client found with this phone number":
      "No Client found with this phone number",
  "Payment list": "Payment list",
  "Colis list": "Colis list",
  "No sector found with governorate data":
      "No sector found with governorate data",
  "Or": "Or",
  "code": "code",
  "Home": "Home",
  "Profile": "Profile",
  "Dashboard": "Dashboard",
  "Colis": "Colis",
  "Client": "Client",
  "Edit Informations": "Edit Informations",
  "governorate": "governorate",
  "City": "City",
  "Region": "Region",
  "Adress": "Adress",
  "Phone number": "Phone number",
  "Sector": "Sector",
  "Colis List": "Colis List",
  "List Manifest": "List Manifest",
  "In progress": "In progress",
  "Clear": "Clear",
  "Select All": "Select All",
  "Add colis": "Add colis",
  "Id": "Id",
  "First name": "First name",
  "Last name": "Last name",
  "Secondary phone number": "Secondary phone number",
  "Governorate": "Governorate",
  "Client adress": "Client adress",
  "Comment": "Comment",
  "Items": "Items",
  "Price (TND)": "Price (TND)",
  "Fragile": "Fragile",
  "Yes": "Yes",
  "No": "No",
  "Exchange": "Exchange",
  "Openable": "Openable",
  "Create": "Create",
  "Phone number is required": "Phone number is required",
  "Name is required": "Name is required",
  "Phone number invalid": "Phone number invalid",
  "Client Name": "Client Name",
  "secondary phone number": "secondary phone number",
  "No sector found": "No sector found",
  "Invalid number": "Invalid number",
  "Manifest": "Manifest",
  "Total price": "Total price",
  "Pickup": "Pickup",
  "Ready for delivery": "Ready for delivery",
  "Sector Ariana": "Sector Ariana",
  "Expeditor account": "Expeditor account",
  "Payment": "Payment",
  "Settings": "Settings",
  "Help & Support": "Help & Support",
  "Accounts": "Accounts",
  "Log Out": "Log Out",
  "Add acount": "Add acount",
  "Email": "Email",
  "Password": "Password",
  "Keep me logged in": "Keep me logged in",
  "Login": "Login",
  "Forgot password": "Forgot password",
  "Email is required": "Email is required",
  "Password is required": "Password is required",
  "Too short. Use at least 8 characters":
      "Too short. Use at least 8 characters",
  "Search": "Search",
  "Runsheet": "Runsheet",
  "Paiement": "Paiement",
  "Retour": "Retour",
  "End of day report": "End of day report",
  "Generate runsheet": "Generate runsheet",
  "you have": "you have",
  "manifest to pickup": "manifest to pickup",
  "Update": "Update",
  "Cin": "Cin",
  "Password (8 or more characters)": "Password (8 or more characters)",
  "Gender": "Gender",
  "Male": "Male",
  "Female": "Female",
  "Other": "Other",
  "Birthday": "Birthday",
  "Matricule": "Matricule",
  "Price": "Price",
  "Save": "Save",
  "Scan code": "Scan code",
  "Notifications": "Notifications",
  "No notifications yet": "No notifications yet",
  "We'll notify you when something arrives":
      "We'll notify you when something arrives",
  "Total revenue this week": "Total revenue this week",
  "Colis delivered": "Colis delivered",
  "Colis canceled": "Colis canceled",
  "Delivery account": "Delivery account",
  "Payment history": "Payment history",
  "Current Week": "Current Week",
  "From": "From",
  "to": "to",
  "Manifest picked": "Manifest picked",
  "User settings": "User settings",
  "App Settings": "App Settings",
  "App theme": "App theme",
  "Notification": "Notification",
  "Privacy preferences": "Privacy preferences",
  "Language": "Language",
  "Report": "Report",
  "Submit a ticket and our Support team will assist you shortly":
      "Submit a ticket and our Support team will assist you shortly",
  "Message": "Message",
  "Send": "Send",
  "your report has been sent to our support team we will contact you as soun as possible":
      "your report has been sent to our support team we will contact you as soun as possible",
  "Incorrect email or password": "Incorrect email or password",
  "Admin": "Admin",
  "Epeditor": "Epeditor",
  "Delivery": "Delivery",
  "Payments": "Payments",
  "Relaunch": "Relaunch",
  "Status": "Status",
  "Delivered": "Delivered",
  "Canceled": "Canceled",
  "Top Expeditor delivered": "Top Expeditor delivered",
  "Top Expeditor canceled": "Top Expeditor canceled",
  "Top agency": "Top agency",
  "Top agency pickup": "Top agency pickup",
  "Top sector canceled": "Top sector canceled",
  "Expeditor name": "Expeditor name",
  "delivered": "delivered",
  "Agency name": "Agency name",
  "Colis pickup": "Colis pickup",
  "Sector name": "Sector name",
  "Admin account": "Admin account",
  "Agency": "Agency",
  "Agency List": "Agency List",
  "Address": "Address",
  "Employee": "Employee",
  "Delete": "Delete",
  "Add agency": "Add agency",
  "Admin List": "Admin List",
  "cancel": "cancel",
  "Confirm": "Confirm",
  "Sector List": "Sector List",
  "Delivery List": "Delivery List",
  "Add sector": "Add sector",
  "Add Admin": "Add Admin",
  "Please enter your Last name": "Please enter your Last name",
  "Cin is required": "Cin is required",
  "Expeditor List": "Expeditor List",
  "Secondary phone number (optional)": "Secondary phone number (optional)",
  "Fiscal Matricule (optional)": "Fiscal Matricule (optional)",
  "Return price": "Return price",
  "Account status": "Account status",
  "Active": "Active",
  "Banned": "Banned",
  "Disabled": "Disabled",
  "Add Expeditor": "Add Expeditor",
  "Price should be greater than 0": "Price should be greater than 0",
  "Too short": "Too short",
  "Wrong name format": "Wrong name format",
  "Expeditor tracking": "Expeditor tracking",
  "Date": "Date",
  "Net price": "Net price",
  "Download": "Download",
  "Recived": "Recived",
  "EXCHANGE": "EXCHANGE",
  "pickup": "pickup",
  "Delivery Payment List": "Delivery Payment List",
  "Not paid": "Not paid",
  "Paid": "Paid",
  "Add Delivery": "Add Delivery",
  "Expeditor Name": "Expeditor Name",
  "Attempt": "Attempt",
  "Return depot": "Return depot",
  "At the depot": "At the depot",
  "At depot": "At depot",
  "In the process of delivery": "In the process of delivery",
  "Appointment": "Appointment",
  "Return colis": "Return colis",
  "Not recived": "Not recived",
  "Payment tracking": "Payment tracking",
  "Client List": "Client List",
  "colis at depot": "colis at depot",
  "colis return to pickup": "colis return to pickup",
  "Done": "Done",
  "Are you sure you want to close this colis?":
      "Are you sure you want to close this colis?",
  "Cancel": "Cancel",
  "Colis Not found or already scanned": "Colis Not found or already scanned",
  "In delivery": "In delivery",
  "Client comment": "Client comment",
  "Client confirmed": "Client confirmed",
  "Rapport de fin de journée": "Rapport de fin de journée",
  "Nombre total des colis livrés": "Nombre total des colis livrés",
  "Nombre des colis retour": "Nombre des colis retour",
  "Nombre des colis echange": "Nombre des colis echange",
  "Total recette": "Total recette",
  "Ok": "Ok",
  "payment to pickup": "payment to pickup",
  "Date: 18-05-2024": "Date: 18-05-2024",
  "Worning": "Worning",
  "Forgot your password": "Forgot your password",
  "Send code": "Send code",
  "Colis per day": "Colis per day",
  "Top clients": "Top clients",
  "Worst clients": "Worst clients",
  "Monday": "Monday",
  "Tuesday": "Tuesday",
  "Wednesday": "Wednesday",
  "Thursday": "Thursday",
  "Friday": "Friday",
  "Saturday": "Saturday",
  "Sunday": "Sunday",
  "Mo": "Mo",
  "Tu": "Tu",
  "We": "We",
  "Th": "Th",
  "Fr": "Fr",
  "Sa": "Sa",
  "Su": "Su",
  "JAN": "JAN",
  "FEB": "FEB",
  "MAR": "MAR",
  "APR": "APR",
  "MAY": "MAY",
  "JUN": "JUN",
  "JUL": "JUL",
  "AOU": "AOU",
  "SEP": "SEP",
  "OCT": "OCT",
  "NOV": "NOV",
  "DEC": "DEC",
  "January": "January",
  "February": "February",
  "March": "March",
  "April": "April",
  "May": "May",
  "June": "June",
  "July": "July",
  "August": "August",
  "September": "September",
  "October": "October",
  "November": "November",
  "December": "December"
};

const frensh = {
  "Name": "Nom",
  "No Client found with this phone number":
      "Aucun client trouvé avec ce numéro de téléphone",
  "Payment list": "Liste de paiement",
  "Colis list": "Liste Colis",
  "No sector found with governorate data":
      "Aucun secteur trouvé avec les données du gouvernorat",
  "Or": "Ou",
  "code": "code",
  "Home": "Accueil",
  "Profile": "Profil",
  "Dashboard": "Tableau de bord",
  "Colis": "Colis",
  "Client": "Client",
  "Edit Informations": "Modifier les informations",
  "governorate": "gouvernorat",
  "City": "Ville",
  "Region": "Région",
  "Adress": "Adresse",
  "Phone number": "Numéro de téléphone",
  "Sector": "Secteur",
  "Colis List": "Liste des colis",
  "List Manifest": "Liste des manifestes",
  "In progress": "En cours",
  "Clear": "Effacer",
  "Select All": "Tout sélectionner",
  "Add colis": "Ajouter un colis",
  "Id": "Id",
  "First name": "Prénom",
  "Last name": "Nom de famille",
  "Secondary phone number": "Numéro de téléphone secondaire",
  "Governorate": "Gouvernorat",
  "Client adress": "Adresse du client",
  "Comment": "Commentaire",
  "Items": "Articles",
  "Price (TND)": "Prix (TND)",
  "Fragile": "Fragile",
  "Yes": "Oui",
  "No": "Non",
  "Exchange": "Échange",
  "Openable": "Ouvrable",
  "Create": "Créer",
  "Phone number is required": "Le numéro de téléphone est requis",
  "Name is required": "Le nom est requis",
  "Phone number invalid": "Numéro de téléphone invalide",
  "Client Name": "Nom du client",
  "secondary phone number": "numéro de téléphone secondaire",
  "No sector found": "Aucun secteur trouvé",
  "Invalid number": "Numéro invalide",
  "Manifest": "Manifeste",
  "Total price": "Prix total",
  "Pickup": "Ramassage",
  "Ready for delivery": "Prêt pour la livraison",
  "Sector Ariana": "Secteur Ariana",
  "Expeditor account": "Compte expéditeur",
  "Payment": "Paiement",
  "Settings": "Paramètres",
  "Help & Support": "Aide & Support",
  "Accounts": "Comptes",
  "Log Out": "Déconnexion",
  "Add acount": "Ajouter un compte",
  "Email": "Email",
  "Password": "Mot de passe",
  "Keep me logged in": "Rester connecté",
  "Login": "Connexion",
  "Forgot password": "Mot de passe oublié",
  "Email is required": "L'email est requis",
  "Password is required": "Le mot de passe est requis",
  "Too short. Use at least 8 characters":
      "Trop court. Utilisez au moins 8 caractères",
  "Search": "Rechercher",
  "Runsheet": "Feuille de route",
  "Paiement": "Paiement",
  "Retour": "Retour",
  "End of day report": "Rapport de fin de journée",
  "Generate runsheet": "Générer la feuille de route",
  "you have": "vous avez",
  "manifest to pickup": "manifeste à ramasser",
  "Update": "Mettre à jour",
  "Cin": "Cin",
  "Password (8 or more characters)": "Mot de passe (8 caractères ou plus)",
  "Gender": "Genre",
  "Male": "Homme",
  "Female": "Femme",
  "Other": "Autre",
  "Birthday": "Anniversaire",
  "Matricule": "Matricule",
  "Price": "Prix",
  "Save": "Sauvegarder",
  "Scan code": "Scanner le code",
  "Notifications": "Notifications",
  "No notifications yet": "Pas encore de notifications",
  "We'll notify you when something arrives":
      "Nous vous informerons lorsque quelque chose arrivera",
  "Total revenue this week": "Revenu total cette semaine",
  "Colis delivered": "Colis livrés",
  "Colis canceled": "Colis annulés",
  "Delivery account": "Compte de livraison",
  "Payment history": "Historique des paiements",
  "Current Week": "Semaine actuelle",
  "From": "De",
  "to": "à",
  "Manifest picked": "Manifeste ramassé",
  "User settings": "Paramètres utilisateur",
  "App Settings": "Paramètres de l'application",
  "App theme": "Thème de l'application",
  "Notification": "Notification",
  "Privacy preferences": "Préférences de confidentialité",
  "Language": "Langue",
  "Report": "Rapport",
  "Submit a ticket and our Support team will assist you shortly":
      "Soumettez un ticket et notre équipe de support vous assistera sous peu",
  "Message": "Message",
  "Send": "Envoyer",
  "your report has been sent to our support team we will contact you as soun as possible":
      "votre rapport a été envoyé à notre équipe de support, nous vous contacterons dès que possible",
  "Incorrect email or password": "Email ou mot de passe incorrect",
  "Admin": "Admin",
  "Epeditor": "Expéditeur",
  "Delivery": "Livraison",
  "Payments": "Paiements",
  "Relaunch": "Relancer",
  "Status": "Statut",
  "Delivered": "Livré",
  "Canceled": "Annulé",
  "Top Expeditor delivered": "Meilleur expéditeur livré",
  "Top Expeditor canceled": "Meilleur expéditeur annulé",
  "Top agency": "Meilleure agence",
  "Top agency pickup": "Meilleur ramassage d'agence",
  "Top sector canceled": "Meilleur secteur annulé",
  "Expeditor name": "Nom de l'expéditeur",
  "delivered": "livré",
  "Agency name": "Nom de l'agence",
  "Colis pickup": "Ramassage de colis",
  "Sector name": "Nom du secteur",
  "Admin account": "Compte administrateur",
  "Agency": "Agence",
  "Agency List": "Liste des agences",
  "Address": "Adresse",
  "Employee": "Employé",
  "Delete": "Supprimer",
  "Add agency": "Ajouter une agence",
  "Admin List": "Liste des administrateurs",
  "cancel": "annuler",
  "Confirm": "Confirmer",
  "Sector List": "Liste des secteurs",
  "Delivery List": "Liste des livraisons",
  "Add sector": "Ajouter un secteur",
  "Add Admin": "Ajouter un administrateur",
  "Please enter your Last name": "Veuillez entrer votre nom de famille",
  "Cin is required": "Cin est requis",
  "Expeditor List": "Liste des expéditeurs",
  "Secondary phone number (optional)":
      "Numéro de téléphone secondaire (optionnel)",
  "Fiscal Matricule (optional)": "Matricule fiscal (optionnel)",
  "Return price": "Prix de retour",
  "Account status": "Statut du compte",
  "Active": "Actif",
  "Banned": "Banni",
  "Disabled": "Désactivé",
  "Add Expeditor": "Ajouter un expéditeur",
  "Price should be greater than 0": "Le prix doit être supérieur à 0",
  "Too short": "Trop court",
  "Wrong name format": "Format de nom incorrect",
  "Expeditor tracking": "Suivi de l'expéditeur",
  "Date": "Date",
  "Net price": "Prix net",
  "Download": "Télécharger",
  "Recived": "Reçu",
  "EXCHANGE": "ÉCHANGE",
  "pickup": "ramassage",
  "Delivery Payment List": "Liste de paiement de livraison",
  "Not paid": "Non payé",
  "Paid": "Payé",
  "Add Delivery": "Ajouter une livraison",
  "Expeditor Name": "Nom de l'expéditeur",
  "Attempt": "Tentative",
  "Return depot": "Retour au dépôt",
  "At the depot": "Au dépôt",
  "At depot": "Au dépôt",
  "In the process of delivery": "En cours de livraison",
  "Appointment": "Rendez-vous",
  "Return colis": "Retour colis",
  "Not recived": "Non reçu",
  "Payment tracking": "Suivi des paiements",
  "Client List": "Liste des clients",
  "colis at depot": "colis au dépôt",
  "colis return to pickup": "colis retour à ramasser",
  "Done": "Terminé",
  "Are you sure you want to close this colis?":
      "Êtes-vous sûr de vouloir fermer ce colis?",
  "Cancel": "Annuler",
  "Colis Not found or already scanned": "Colis non trouvé ou déjà scanné",
  "In delivery": "En livraison",
  "Client comment": "Commentaire du client",
  "Client confirmed": "Client confirmé",
  "Rapport de fin de journée": "Rapport de fin de journée",
  "Nombre total des colis livrés": "Nombre total des colis livrés",
  "Nombre des colis retour": "Nombre des colis retour",
  "Nombre des colis echange": "Nombre des colis échange",
  "Total recette": "Recette totale",
  "Ok": "Ok",
  "payment to pickup": "paiement à ramasser",
  "Worning": "Avertissement",
  "Forgot your password": "Mot de passe oublié",
  "Send code": "Envoyer le code",
  "Colis per day": "Colis par jour",
  "Top clients": "Meilleurs clients",
  "Worst clients": "Pires clients",
  "Monday": "Lundi",
  "Tuesday": "Mardi",
  "Wednesday": "Mercredi",
  "Thursday": "Jeudi",
  "Friday": "Vendredi",
  "Saturday": "Samedi",
  "Sunday": "Dimanche",
  "Mo": "Lu",
  "Tu": "Ma",
  "We": "Me",
  "Th": "Je",
  "Fr": "Ve",
  "Sa": "Sa",
  "Su": "Di",
  "JAN": "JAN",
  "FEB": "FÉV",
  "MAR": "MAR",
  "APR": "AVR",
  "MAY": "MAI",
  "JUN": "JUN",
  "JUL": "JUL",
  "AOU": "AOÛ",
  "SEP": "SEP",
  "OCT": "OCT",
  "NOV": "NOV",
  "DEC": "DÉC",
  "January": "Janvier",
  "February": "Février",
  "March": "Mars",
  "April": "Avril",
  "May": "Mai",
  "June": "Juin",
  "July": "Juillet",
  "August": "Août",
  "September": "Septembre",
  "October": "Octobre",
  "November": "Novembre",
  "December": "Décembre"
};

const arabe = {
  "Name": "اسم",
  "No Client found with this phone number":
      "لم يتم العثور على عميل برقم الهاتف هذا",
  "Payment list": "قائمة الدفع",
  "Colis list": "قائمةالطرود",
  "No sector found with governorate data":
      "لم يتم العثور على قطاع يحتوي على بيانات المحافظة",
  "Or": "أو",
  "Code": "كود",
  "Home": "الصفحة الرئيسية",
  "Profile": "الملف الشخصي",
  "Dashboard": "لوحة القيادة",
  "Colis": "الطرود",
  "Client": "العميل",
  "Edit Informations": "تعديل المعلومات",
  "governorate": "المحافظة",
  "City": "المدينة",
  "Region": "المنطقة",
  "Adress": "العنوان",
  "Phone number": "رقم الهاتف",
  "Sector": "القطاع",
  "Colis List": "قائمة الطرود",
  "List Manifest": "قائمة البيانات",
  "In progress": "قيد التنفيذ",
  "Clear": "مسح",
  "Select All": "تحديد الكل",
  "Add colis": "إضافة طرد",
  "Id": "المعرف",
  "First name": "الاسم الأول",
  "Last name": "الاسم الأخير",
  "Secondary phone number": "رقم الهاتف الثانوي",
  "Governorate": "المحافظة",
  "Client adress": "عنوان العميل",
  "Comment": "تعليق",
  "Items": "العناصر",
  "Price (TND)": "السعر (دينار تونسي)",
  "Fragile": "قابل للكسر",
  "Yes": "نعم",
  "No": "لا",
  "Exchange": "تبادل",
  "Openable": "قابل للفتح",
  "Create": "إنشاء",
  "Phone number is required": "رقم الهاتف مطلوب",
  "Name is required": "الاسم مطلوب",
  "Phone number invalid": "رقم الهاتف غير صالح",
  "Client Name": "اسم العميل",
  "secondary phone number": "رقم الهاتف الثانوي",
  "No sector found": "لم يتم العثور على قطاع",
  "Invalid number": "رقم غير صالح",
  "Manifest": "البيان",
  "Total price": "السعر الإجمالي",
  "Pickup": "الاستلام",
  "Ready for delivery": "جاهز للتسليم",
  "Sector Ariana": "قطاع أريانة",
  "Expeditor account": "حساب المرسل",
  "Payment": "الدفع",
  "Settings": "الإعدادات",
  "Help & Support": "المساعدة والدعم",
  "Accounts": "الحسابات",
  "Log Out": "تسجيل الخروج",
  "Add acount": "إضافة حساب",
  "Email": "البريد الإلكتروني",
  "Password": "كلمة المرور",
  "Keep me logged in": "إبقاء تسجيل الدخول",
  "Login": "تسجيل الدخول",
  "Forgot password": "نسيت كلمة المرور",
  "Email is required": "البريد الإلكتروني مطلوب",
  "Password is required": "كلمة المرور مطلوبة",
  "Too short. Use at least 8 characters": "قصير جدًا. استخدم 8 أحرف على الأقل",
  "Search": "بحث",
  "Runsheet": "ورقة العمل",
  "Paiement": "الدفع",
  "Retour": "العودة",
  "End of day report": "تقرير نهاية اليوم",
  "Generate runsheet": "إنشاء ورقة العمل",
  "you have": "لديك",
  "manifest to pickup": "بيان للاستلام",
  "Update": "تحديث",
  "Cin": "رقم الهوية",
  "Password (8 or more characters)": "كلمة المرور (8 أحرف أو أكثر)",
  "Gender": "الجنس",
  "Male": "ذكر",
  "Female": "أنثى",
  "Other": "آخر",
  "Birthday": "تاريخ الميلاد",
  "Matricule": "الرقم التسلسلي",
  "Price": "السعر",
  "Save": "حفظ",
  "Scan code": "مسح الرمز",
  "Notifications": "الإشعارات",
  "No notifications yet": "لا توجد إشعارات بعد",
  "We'll notify you when something arrives": "سوف نخطرك عندما يصل شيء",
  "Total revenue this week": "الإيرادات الإجمالية هذا الأسبوع",
  "Colis delivered": "الطرود المسلمة",
  "Colis canceled": "الطرود الملغاة",
  "Delivery account": "حساب التسليم",
  "Payment history": "تاريخ الدفع",
  "Current Week": "الأسبوع الحالي",
  "From": "من",
  "to": "إلى",
  "Manifest picked": "تم استلام البيان",
  "User settings": "إعدادات المستخدم",
  "App Settings": "إعدادات التطبيق",
  "App theme": "موضوع التطبيق",
  "Notification": "الإشعار",
  "Privacy preferences": "تفضيلات الخصوصية",
  "Language": "اللغة",
  "Report": "تقرير",
  "Submit a ticket and our Support team will assist you shortly":
      "أرسل تذكرة وسيساعدك فريق الدعم لدينا قريبًا",
  "Message": "رسالة",
  "Send": "إرسال",
  "your report has been sent to our support team we will contact you as soun as possible":
      "تم إرسال تقريرك إلى فريق الدعم لدينا وسنتصل بك في أقرب وقت ممكن",
  "Incorrect email or password": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
  "Admin": "مسؤول",
  "Epeditor": "مرسل",
  "Delivery": "التسليم",
  "Payments": "المدفوعات",
  "Relaunch": "إعادة الإطلاق",
  "Status": "الحالة",
  "Delivered": "تم التسليم",
  "Canceled": "تم الإلغاء",
  "Top Expeditor delivered": "أفضل مرسل تم تسليمه",
  "Top Expeditor canceled": "أفضل مرسل تم إلغاؤه",
  "Top agency": "أفضل وكالة",
  "Top agency pickup": "أفضل استلام من الوكالة",
  "Top sector canceled": "أفضل قطاع تم إلغاؤه",
  "Expeditor name": "اسم المرسل",
  "delivered": "تم التسليم",
  "Agency name": "اسم الوكالة",
  "Colis pickup": "استلام الطرد",
  "Sector name": "اسم القطاع",
  "Admin account": "حساب المسؤول",
  "Agency": "الوكالة",
  "Agency List": "قائمة الوكالات",
  "Address": "العنوان",
  "Employee": "الموظف",
  "Delete": "حذف",
  "Add agency": "إضافة وكالة",
  "Admin List": "قائمة المسؤولين",
  "cancel": "إلغاء",
  "Confirm": "تأكيد",
  "Sector List": "قائمة القطاعات",
  "Delivery List": "قائمة التسليم",
  "Add sector": "إضافة قطاع",
  "Add Admin": "إضافة مسؤول",
  "Please enter your Last name": "يرجى إدخال اسم العائلة",
  "Cin is required": "رقم الهوية مطلوب",
  "Expeditor List": "قائمة المرسلين",
  "Secondary phone number (optional)": "رقم الهاتف الثانوي (اختياري)",
  "Fiscal Matricule (optional)": "الرقم التسلسلي الضريبي (اختياري)",
  "Return price": "سعر العودة",
  "Account status": "حالة الحساب",
  "Active": "نشط",
  "Banned": "محظور",
  "Disabled": "معطل",
  "Add Expeditor": "إضافة مرسل",
  "Price should be greater than 0": "يجب أن يكون السعر أكبر من 0",
  "Too short": "قصير جدًا",
  "Wrong name format": "تنسيق الاسم غير صحيح",
  "Expeditor tracking": "تتبع المرسل",
  "Date": "التاريخ",
  "Net price": "السعر الصافي",
  "Download": "تحميل",
  "Recived": "تم الاستلام",
  "EXCHANGE": "تبادل",
  "pickup": "استلام",
  "Delivery Payment List": "قائمة دفع التسليم",
  "Not paid": "غير مدفوع",
  "Paid": "مدفوع",
  "Add Delivery": "إضافة تسليم",
  "Expeditor Name": "اسم المرسل",
  "Attempt": "محاولة",
  "Return depot": "عودة إلى المستودع",
  "At the depot": "في المستودع",
  "At depot": "في المستودع",
  "In the process of delivery": "في عملية التسليم",
  "Appointment": "موعد",
  "Return colis": "عودة الطرد",
  "Not recived": "لم يتم الاستلام",
  "Payment tracking": "تتبع الدفع",
  "Client List": "قائمة العملاء",
  "colis at depot": "الطرود في المستودع",
  "colis return to pickup": "عودة الطرود للاستلام",
  "Done": "تم",
  "Are you sure you want to close this colis?":
      "هل أنت متأكد من أنك تريد إغلاق هذا الطرد؟",
  "Cancel": "إلغاء",
  "Colis Not found or already scanned": "الطرد غير موجود أو تم مسحه بالفعل",
  "In delivery": "في التسليم",
  "Client comment": "تعليق العميل",
  "Client confirmed": "تم تأكيد العميل",
  "Rapport de fin de journée": "تقرير نهاية اليوم",
  "Nombre total des colis livrés": "إجمالي عدد الطرود المسلمة",
  "Nombre des colis retour": "عدد الطرود المرتجعة",
  "Nombre des colis echange": "عدد الطرود المتبادلة",
  "Total recette": "الإيرادات الإجمالية",
  "Ok": "حسنًا",
  "payment to pickup": "الدفع للاستلام",
  "Date: 18-05-2024": "التاريخ: 18-05-2024",
  "Worning": "تحذير",
  "Forgot your password": "نسيت كلمة المرور؟",
  "Send code": "إرسال الرمز",
  "Colis per day": "الطرود يوميًا",
  "Top clients": "أفضل العملاء",
  "Worst clients": "أسوأ العملاء",
  "Monday": "الاثنين",
  "Tuesday": "الثلاثاء",
  "Wednesday": "الأربعاء",
  "Thursday": "الخميس",
  "Friday": "الجمعة",
  "Saturday": "السبت",
  "Sunday": "الأحد",
  "Mo": "الإثنين",
  "Tu": "الثلاثاء",
  "We": "الأربعاء",
  "Th": "الخميس",
  "Fr": "الجمعة",
  "Sa": "السبت",
  "Su": "الأحد",
  "JAN": "يناير",
  "FEB": "فبراير",
  "MAR": "مارس",
  "APR": "أبريل",
  "MAY": "مايو",
  "JUN": "يونيو",
  "JUL": "يوليو",
  "AOU": "أغسطس",
  "SEP": "سبتمبر",
  "OCT": "أكتوبر",
  "NOV": "نوفمبر",
  "DEC": "ديسمبر",
  "January": "يناير",
  "February": "فبراير",
  "March": "مارس",
  "April": "أبريل",
  "May": "مايو",
  "June": "يونيو",
  "July": "يوليو",
  "August": "أغسطس",
  "September": "سبتمبر",
  "October": "أكتوبر",
  "November": "نوفمبر",
  "December": "ديسمبر"
};

const supportedLanguages = ['English', 'French', 'Arabe'];
