// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBrXaRC7xcvwYlv6xQ3zVImkrgCMM5YVU',
    appId: '1:86647914195:web:71ea8a7ab0b79ca1a39e26',
    messagingSenderId: '86647914195',
    projectId: 'jetpack-128ea',
    authDomain: 'jetpack-128ea.firebaseapp.com',
    storageBucket: 'jetpack-128ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYRng-uwximRrjfKllxlD0qCGHOV21-vk',
    appId: '1:86647914195:android:3a6b6e38fe067b92a39e26',
    messagingSenderId: '86647914195',
    projectId: 'jetpack-128ea',
    storageBucket: 'jetpack-128ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX5WGR9PUwWOTEpA_ZJN6M4b68SLmLgh4',
    appId: '1:86647914195:ios:00100ca230618685a39e26',
    messagingSenderId: '86647914195',
    projectId: 'jetpack-128ea',
    storageBucket: 'jetpack-128ea.appspot.com',
    iosBundleId: 'com.example.jetpack',
  );
}
